spring:
 application:
  name: databet-social
server:
 port: 8093
management:
 server:
  port: 8094

eureka:
 client:
  healthcheck:
   enabled: true
  serviceUrl:
   defaultZone: http://localhost:8043/eureka/
