spring:
 application:
  name: databet-stats
server:
 port: 8073
management:
 server:
  port: 8074

eureka:
 client:
  healthcheck:
   enabled: true
  serviceUrl:
   defaultZone: http://localhost:8043/eureka/
