spring:
 application:
  name: databet-cotes
server:
 port: 8083
management:
 server:
  port: 8084

eureka:
 client:
  healthcheck:
   enabled: true
  serviceUrl:
   defaultZone: http://localhost:8043/eureka/