spring:
 application:
  name: databet-gateway

 cloud:
  gateway:
   routes:
   - id: method_route
     uri: http://localhost
     predicates:
     - Method=GET
   - id: databet-ref
     uri: localhost:8053
   - id: database-cotes
     uri: localhost:9998
   - id: database-social
     uri: localhost:9997
   - id: database-stats
     uri: localhost:9996
  
server:
 port: 8023
 servlet:
  context-path: /api
management:
 server:
  port: 8024
