spring:
 application:
  name: databet-eureka
  
server:
 port: 8043
management:
 server:
  port: 8044
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    healthcheck:
      enabled: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
   com:
    netflix: debug