spring:
 application:
  name: databet-ref

 data:
  mongodb:
   host: localhost
   port: 27017
   database: admin
   user: admin
   password: admin
  
server:
 port: 8053
management:
 server:
 port: 8054
