spring:
 application:
  name: databet-ref

 data:
  mongodb:
   host: localhost
   port: 27017
   database: databet-ref
   user: admin
   password: admin
  
server:
 port: 8053
# servlet:
#  context-path: /api
management:
 server:
  port: 8054
 
eureka:
 client:
  healthcheck:
   enabled: true
  serviceUrl:
   defaultZone: http://localhost:8043/eureka/
